import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SongPlayer from './ui/SongPlayer';
const inter = Inter({ subsets: ['latin'] });
import Image from 'next/image';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${inter.className} overflow-hidden bg-[#181818] min-w-full min-h-full scroll-smooth`}>
                <div id="app" className="relative h-screen gap-2">
                    <aside className="[grid-area:aside] bg-[#1212124b] overflow-hidden backdrop-blur-sm  rounded-lg ml-4 pt-4 mt-4 max-h-full min-h-full flex flex-col items-center justify-center">
                        <p>aaa</p>
                        <p>aaa</p>
                        <Image
                            src={'/images/bg2.webp'}
                            alt="bg"
                            draggable={false}
                            priority
                            quality={100}
                            decoding="async"
                            loading="eager"
                            fill
                            style={{
                                width: '100%',
                                height: '100%',
                            }}
                            className="object-cover grayscale object-center w-full fixed blur-sm opacity-50 inset-0 -z-10"
                        />
                    </aside>
                    <main className="[grid-area:main] mt-4 pr-4 z-50 overflow-hidden w-full h-full">
                        {children}
                    </main>

                    <div className="[grid-area:player] h-[10vh] flex items-center overflow-hidden">
                        <SongPlayer />
                    </div>
                </div>
            </body>
        </html>
    );
}
