import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SongPlayer from './ui/SongPlayer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${inter.className} overflow-hidden w-full h-full scroll-smooth`}>
                {children}
                <div className=" fixed bottom-0 left-0 right-0 overflow-hidden">
                    <SongPlayer />
                </div>
            </body>
        </html>
    );
}
