import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SongPlayer from './ui/SongPlayer';
const inter = Inter({ subsets: ['latin'] });
import Image from 'next/image';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${inter.className} overflow-hidden min-w-full min-h-full scroll-smooth`}>
                <main className=" z-50">{children}</main>
                <div className=" fixed bottom-0 left-0 right-0 overflow-hidden">
                    <SongPlayer />
                </div>
                <Image
                    src={'/images/bg.webp'}
                    alt="bg"
                    draggable={false}
                    priority
                    quality={100}
                    fill
                    style={{ width: '100%', height: '100%' }}
                    className="object-cover fixed opacity-50 inset-0 blur-sm -z-10"
                />
            </body>
        </html>
    );
}
